PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZMCP_SERVERS-AREA .
    FIELD ZMCP_SERVERS-SERVER .
    FIELD ZMCP_SERVERS-CLASS .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZMCP_SERVERS-AREA .
    FIELD ZMCP_SERVERS-SERVER .
  module detail_pai.
 endchain.
