PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZMCP_CONFIG-LOG_LEVEL .
    FIELD ZMCP_CONFIG-OBJECT .
    FIELD ZMCP_CONFIG-SUBOBJECT .
    FIELD ZMCP_CONFIG-CORS_MODE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
  module detail_pai.
 endchain.
