PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZMCP_ORIGINS-AREA .
    FIELD ZMCP_ORIGINS-SERVER .
    FIELD ZMCP_ORIGINS-ORIGIN .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZMCP_ORIGINS-AREA .
    FIELD ZMCP_ORIGINS-SERVER .
    FIELD ZMCP_ORIGINS-ORIGIN .
  module detail_pai.
 endchain.
